name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  DrakhtarBuild:
    name: Building Drakhtar
    runs-on: windows-latest
    if: "!contains(needs.pre_ci.outputs.commit_message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install Dependencies
        run: pwsh -File .\scripts\windows-setup.ps1
        shell: pwsh
      - uses: ammaraskar/msvc-problem-matcher@master
      - name: Build Project
        run: pwsh -File .\scripts\windows-build.ps1
        shell: pwsh
